### PR TITLE
Nii236/largest permutation

### PR DESCRIPTION
**Pull request by nii236**

### CODE REVIEW

**Comment by phuongy** [comment]
Is this all working?

**Comment by ghost** [comment]
@nii236, have some courtesy for repository cleanliness and squash all those commits down please.

**Comment by nii236** [comment]
@miqid: What is your policy on squashing commits then? You'd just want a single commit per PR?

**Comment by nii236** [comment]
@phuongy: it passes the smaller tests, but not the giant one. Still in progress

**Comment by ghost** [comment]
@nii236, not necessarily a single commit. I'd personally aggregate all changes that logically belong with one another (i.e. as a base solution, as tests for a solution) and remove all housekeeping commits like merges and reverts, unless the pull request is specifically to do housekeeping. Revisions in response to pull request discussion also benefit (i.e. visibility of amendments) as additional commits. Everybody's care factor differs, but that's just my two cents. :neckbeard:

**Pull request merged**
